// src/game/state.js — the single mutable game-state object.
// Imported (not reassigned) by main.js and render/loop modules; its fields are
// mutated in place each frame. resetGame()/startRun() in main.js re-initialise it.
export const game = {
  status: "idle",
  player: { x: 360, y: 230, r: 16, speed: 270 },
  playerVariant: 0,
  backdropVariant: 0,
  bossVariant: 0,
  arenaProps: [],
  hazards: [],
  orbs: [],
  powerUps: [],
  lasers: [],
  bolts: [],
  fireTimer: 0,
  fx: [],
  particles: [],
  shockwaves: [],
  floatingTexts: [],
  boss: null,
  bossSpawned: false,
  score: 0,
  orbCount: 0,
  health: 3,
  shield: 0,
  magnetTimer: 0,
  scoreBoostTimer: 0,
  phaseTimer: 0,
  combo: 1,
  maxCombo: 1,
  comboTimer: 0,
  elapsed: 0,
  invulnerable: 0,
  nextPowerUpAt: 5,
  nextHazardAt: 10,
  inputX: 0,
  inputY: 0,
  pointerActive: false,
  pointerX: 360,
  pointerY: 230,
  shake: 0,
  flash: 0,
  worldTime: 0,
  hitstop: 0, // seconds of frame-freeze remaining (E3)
  paceSamples: [] // score at end of each whole second this run (E2)
};
